nodes:
  - name: ojo
    ip: 192.168.1.96
    user: ojo
    emoji: "ğŸ¦"
    deps: ".[vla]"
  - name: trossen-ai
    ip: 192.168.1.97
    user: trossen-ai
    emoji: "ğŸ¦¾"
    deps: ".[bot,tag]"
  - name: ook
    ip: 192.168.1.90
    user: ook
    emoji: "ğŸ¦§"
    deps: ".[gen]"
  - name: rpi1
    ip: 192.168.1.98
    user: rpi1
    emoji: "ğŸ“"
    deps: ".[tag]"
  - name: rpi2
    ip: 192.168.1.99
    user: rpi2
    emoji: "ğŸ‡"
    deps: ".[viz]"
  - name: oop
    ip: 192.168.1.51
    user: oop
    emoji: "ğŸ¦Š"
    deps: "."