nodes:
  - name: ojo
    ip: 192.168.1.96
    user: ojo
    emoji: "ğŸ¦"
  - name: trossen-ai
    ip: 192.168.1.97
    user: trossen
    emoji: "ğŸ¦¾"
  - name: ook
    ip: 192.168.1.100
    user: ook
    emoji: "ğŸ¦§"
  - name: rpi1
    ip: 192.168.1.98
    user: pi
    emoji: "ğŸ¥§"
  - name: rpi2
    ip: 192.168.1.99
    user: pi
    emoji: "ğŸ«"
  - name: oop
    ip: 192.168.1.53
    user: oop
    emoji: "ğŸ¦Š"