nodes:
  - name: ojo
    ip: 192.168.1.96
    user: ojo
    emoji: "ğŸ¦"
  - name: trossen-ai
    ip: 192.168.1.97
    user: trossen-ai
    emoji: "ğŸ¦¾"
  - name: rpi1
    ip: 192.168.1.98
    user: rpi1
    emoji: "ğŸ“"
  - name: rpi2
    ip: 192.168.1.99
    user: rpi2
    emoji: "ğŸ‡"
  - name: ook
    ip: 192.168.1.90
    user: ook
    emoji: "ğŸ¦§"
  - name: oop
    ip: 192.168.1.51
    user: oop
    emoji: "ğŸ¦Š"